#!/usr/bin/env bash
# host/10-packages — pacman explicit list + yay bootstrap + AUR list.
# Lists live in the tracked payload at host/meta/ (regenerated by
# scripts/sync-from-host.sh on the live box).
set -euo pipefail
. "$(dirname "$0")/../../lib/common.sh"

[ -f "$PAYLOAD_DIR/meta/packages-explicit.list" ] \
  || die "no host/meta/packages-explicit.list — regenerate with scripts/sync-from-host.sh on the live box"
[ -f "$PAYLOAD_DIR/meta/packages-aur.list" ] \
  || die "no host/meta/packages-aur.list — regenerate with scripts/sync-from-host.sh on the live box"

echo "  refreshing mirrors + base updates"
sudo pacman -Syyu --noconfirm

# The explicit list contains everything `pacman -Qqe` reported — including
# AUR-installed packages (sunshine, yay-bin, ...) that the repos don't know.
# Filter the AUR names out of the pacman pass; they're handled by yay below.
mapfile -t pkgs < <(grep -vE '^\s*(#|$)' "$PAYLOAD_DIR/meta/packages-explicit.list" \
  | grep -Fxv -f "$PAYLOAD_DIR/meta/packages-aur.list")

echo "  installing explicit pacman packages (${#pkgs[@]} pkgs)"
# HONESTY NOTE: `pacman -S a b c` is a single transaction — one unknown
# target (a package renamed/dropped from the repos since the list was synced)
# aborts the WHOLE transaction and installs NOTHING. So if the bulk fast-path
# fails, fall back to per-package installs, collect the stragglers, and warn
# at the end instead of dying mid-bootstrap.
failed=()
if ! sudo pacman -S --needed --noconfirm "${pkgs[@]}"; then
  warn "bulk pacman transaction failed — retrying packages individually (slow but resilient)"
  for p in "${pkgs[@]}"; do
    sudo pacman -S --needed --noconfirm "$p" >/dev/null || failed+=("$p")
  done
fi

if ! command -v yay >/dev/null; then
  echo "  bootstrapping yay (one-time)"
  ensure_pkg base-devel git
  tmp=$(mktemp -d)
  trap 'rm -rf "$tmp"' EXIT
  git clone --depth=1 https://aur.archlinux.org/yay-bin.git "$tmp/yay-bin"
  (cd "$tmp/yay-bin" && makepkg -si --noconfirm)
fi

echo "  installing AUR packages ($(wc -l <"$PAYLOAD_DIR/meta/packages-aur.list") pkgs)"
mapfile -t aur < <(grep -vE '^yay-bin($|-debug$)' "$PAYLOAD_DIR/meta/packages-aur.list")
# No `|| true` here: a yay failure (network, PKGBUILD break) must fail the
# stage — sunshine/coolercontrold silently missing is worse than an abort.
if [ ${#aur[@]} -gt 0 ]; then
  yay -S --needed --noconfirm "${aur[@]}"
fi

if [ ${#failed[@]} -gt 0 ]; then
  warn "pacman could not install: ${failed[*]}"
  warn "  (renamed/dropped from the repos? fix host/meta/packages-explicit.list and re-run)"
fi

ok "packages installed"
