audio_sink = BinauralBus
capture = kms
channels = 1
csrf_allowed_origins = https://172.16.1.220:47990,https://localhost:47990,https://gameland:47990,https://Gameland:47990
encoder = nvenc
fec_percentage = 5
gamepad = xone
keyboard = disabled
max_bitrate = 50000
min_log_level = debug
mouse = disabled
nvenc_preset = 5
nvenc_spatial_aa = disabled
sunshine_name = Gameland
system_tray = disabled
