title   Arch Linux
linux   /vmlinuz-linux
initrd  /amd-ucode.img
initrd  /initramfs-linux.img
options root=UUID=cd960439-f564-4728-b32f-e657691dad30 rw resume=UUID=6919723e-bf81-4ed1-8dea-629f25d234b9 iommu=pt nvidia_drm.modeset=1 acpi_enforce_resources=lax nvidia_drm.fbdev=1 drm.edid_firmware=HDMI-A-1:edid/steamdeck.bin video=HDMI-A-1:e
