#!/usr/bin/env bash
# scripts/gen-dashboard-configmap.sh — regenerate the Grafana dashboard
# ConfigMap from its JSON.
#
# cluster/monitoring/dashboards/gpu-node-overview.json is the SOURCE OF
# TRUTH. Never edit the generated *-configmap.yaml by hand — change the
# JSON and rerun this script. (Editing the dashboard in the Grafana UI
# doesn't persist either: the sidecar overwrites it from the ConfigMap.)
#
# Pipeline:
#   kubectl create configmap --dry-run=client -o yaml   (no cluster access
#   needed), then inject the two bits of metadata the sidecar needs:
#     metadata.labels.grafana_dashboard: "1"        # sidecar pickup selector
#     metadata.annotations.grafana_folder: gpu-node # Grafana folder
#   via yq when installed, else a stdlib-only python3 text pass. No PyYAML —
#   a YAML round-trip would mangle the literal block scalar holding the JSON.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DASH_DIR="$REPO_ROOT/cluster/monitoring/dashboards"
JSON="$DASH_DIR/gpu-node-overview.json"
OUT="$DASH_DIR/gpu-node-overview-configmap.yaml"

command -v kubectl >/dev/null 2>&1 || { echo "kubectl not found" >&2; exit 1; }
[ -f "$JSON" ] || { echo "missing $JSON" >&2; exit 1; }

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

kubectl create configmap gpu-node-overview-dashboard \
  --from-file="gpu-node-overview.json=$JSON" \
  --namespace observability --dry-run=client -o yaml > "$TMP"

# Deliberately NOT using yq even when installed: different yq flavors
# (mikefarah vs python-yq) serialize differently, so the committed file would
# churn depending on who regenerates it. One canonical stdlib serializer:
python3 - "$TMP" <<'PY'
import sys
path = sys.argv[1]
out = []
for line in open(path):
    if line.rstrip("\n") == "  creationTimestamp: null":
        continue
    out.append(line)
    if line.rstrip("\n") == "metadata:":
        out.append('  labels:\n    grafana_dashboard: "1"\n')
        out.append('  annotations:\n    grafana_folder: gpu-node\n')
open(path, "w").write("".join(out))
PY

{
  echo "# GENERATED by scripts/gen-dashboard-configmap.sh — DO NOT EDIT BY HAND."
  echo "# Source of truth: cluster/monitoring/dashboards/gpu-node-overview.json"
  echo "# Edit the JSON, rerun the script, then: kubectl apply -f <this file>"
  cat "$TMP"
} > "$OUT"

echo "wrote ${OUT#"$REPO_ROOT"/}"
echo "apply:   kubectl apply -f $OUT"
echo "verify:  kubectl -n observability logs deploy/prometheus-stack-grafana -c grafana-sc-dashboard --tail=10"
